[tool.poetry]
name = "demoqa_playwright"
version = "0.1.0"
description = ""
authors = ["User <user@example.com>"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
pytest-playwright = "^0.7.1"

[tool.poetry.group.dev.dependencies]
pytest = "^8.0.0"
